# Generated by Django 3.1 on 2021-03-21 11:51

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefile',
            name='file',
            field=models.FileField(upload_to=course.models.course_directory_path),
        ),
    ]
