# Generated by Django 3.1 on 2021-03-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20210321_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='promo_image_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bildetekst, skriv f.eks. kildehenvisning til bildet.'),
        ),
    ]
