# Generated by Django 3.1 on 2021-04-02 14:05

from django.db import migrations, models
import notebook.models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_auto_20210321_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='file_html',
            field=models.FileField(blank=True, storage=notebook.models.OverwriteStorage(), upload_to='notebooks', verbose_name='.html file'),
        ),
    ]
